### ISSUE TITLE
Chimerashot triggering entrapment root

### ISSUE THREAD

**Issue by Ravencrest-WoW** [Ravencrest-WoW/Bugtracker#1]
[Issue]: Chimerashot does trigger entrapment root if the target is under the influence of ice or snaketrap

[Steps to reproduce the problem]: If i use icetrap or snaketrap on a target to trigger the entrapment root and then use chimera on it, it will root them again. This is kinda gamebreaking since hunters now have a root every 9 seconds with chimera if they use snake or icetrap before.

**Comment by Ravencrest-WoW** [comment]
Resolved

**Comment by Cillez** [comment]
Fixed

Commit: 8cea8400
